name: MindsDB Releases

on:
  release:
    types: [published]
    paths-ignore:
      - 'docs/**'
      - 'README.md'

jobs:

  build_amis_packer:
   #TODO: in the future migrate to https://github.com/hashicorp/packer-github-actions, when we can send config as an url
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3.5.3
      - name: Deploy AMI's
        env:
          ACCESS_KEY:  ${{ secrets.GH_ACCESS_KEY }}
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #NOTE: Send variables to packer build command or var file, because if using env in conf they are not vissible to build
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get install packer
          python create_version_file.py release
          mdb_version=`cat distributions/ver/dist/stable_version.txt`
          export MINDSDB_VERSION="$mdb_version"
          git clone https://${ACCESS_KEY}@github.com/mindsdb/mindsdb_gateway
          cd mindsdb_gateway/deployments
          echo "Building AMIs for $MINDSDB_VERSION"
          sudo packer build -var "mindsdb_version=$MINDSDB_VERSION" -var "acces_key=$ACCESS_KEY" -var "aws_acces_key=$AWS_ACCESS_KEY" -var "aws_secret_key=$AWS_SECRET_KEY" -parallel-builds=2 config.json

  create_version_file:
    runs-on: ubuntu-latest
    needs: build_amis_packer
    steps:
    - uses: actions/checkout@v3.5.3
    - name: Set up Python
      uses: actions/setup-python@v4.7.0
      with:
        python-version: '3.7'
    - name: Create version files
      run: |
        python create_version_file.py release

    - name: Sync version file to s3
      uses: jakejarvis/s3-sync-action@master
      with:
        args: --acl public-read --follow-symlinks
      env:
        AWS_S3_BUCKET: 'mindsdb-installer'
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'us-west-2'
        SOURCE_DIR: 'distributions/ver/dist'
        DEST_DIR: 'mindsdb-installer/ver'


  deploy_to_dockerhub:
      runs-on: ubuntu-latest
      needs: create_version_file
      steps:
        - uses: actions/checkout@v3.5.3
        - name: Docker Login
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
            
        - name: Docker build and push
          run: |
            cd docker
            python3 build.py release
